name = "liuyao-ai"
main = "worker.js"
compatibility_date = "2025-06-11"

# 环境变量
[vars]
# API_KEY = ""
MODEL = "deepseek/deepseek-chat-v3-0324"
ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"
SYSTEM_PROMPT = ""

# 静态资产配置
[assets]
directory = "./static"
binding = "ASSETS" 