name = "liuyao-ai"
main = "worker.js"
compatibility_date = "2025-06-11"

# 环境变量（示例）
[vars]
# 配置你的AI API相关环境变量
# API_KEY = ""
# MODEL = ""
# ENDPOINT = ""
# SYSTEM_PROMPT = ""

# 静态资产配置
[assets]
directory = "."
include = ["*.html", "*.css", "*.js", "*.json", "*.png", "*.ico", "*.txt", "assets/**/*", "manifest.json", "web-manifest-combined.json", "service-worker.js"]
exclude = ["node_modules/**", ".git/**", ".wrangler/**", "*.md", "package*.json", "wrangler.toml", "worker.js", "functions/**", "lib/**", ".dev.vars*"]
binding = "ASSETS" 