name = "oracloud"
main = "worker.js"
compatibility_date = "2025-06-24"

# 环境变量
# 本地调试请在项目根目录创建 `.dev.vars` 文件，Wrangler 会在 `wrangler dev` 运行时自动加载。
# 该文件中的变量优先级高于本段 [vars] 配置，且由于已在 .gitignore 中列出，不会被提交到 Git。
# 文件格式示例（KEY="value"，每行一个）：
#   API_KEY="your-local-api-key"
#   MODEL="deepseek/deepseek-chat-v3-0324"
[vars]
# "price"：优先选择最低价格
# "throughput": 优先选择吞吐量最高的模型
# "latency": 优先选择最低延迟
OPENROUTER_SORT = "price"
MODEL = "deepseek/deepseek-chat-v3-0324"
TITLE_MODEL = "google/gemini-2.5-flash-lite-preview-06-17"
REASONING_MODEL = "deepseek/deepseek-r1-0528"
ENDPOINT = "https://gateway.ai.cloudflare.com/v1/9ce9598718c27c7441e2818185c1dbfa/openrouter/openrouter/v1/chat/completions"
# API_KEY = ""
# SYSTEM_PROMPT = "你是一位精通小六壬的占卜师"

# 静态资产配置
[assets]
directory = "./static"
binding = "ASSETS" 
