name = "liuyao-ai"
main = "worker.js"
compatibility_date = "2025-06-11"

# 环境变量
# 本地调试请在项目根目录创建 `.dev.vars` 文件，Wrangler 会在 `wrangler dev` 运行时自动加载。
# 该文件中的变量优先级高于本段 [vars] 配置，且由于已在 .gitignore 中列出，不会被提交到 Git。
# 文件格式示例（KEY="value"，每行一个）：
#   API_KEY="your-local-api-key"
#   MODEL="deepseek/deepseek-chat-v3-0324"
[vars]
# API_KEY = ""
REASONING_MODEL = "anthropic/claude-sonnet-4"
MODEL = "deepseek/deepseek-chat-v3-0324"
ENDPOINT = "https://openrouter.ai/api/v1/chat/completions"
# SYSTEM_PROMPT = "你是一位精通小六壬的占卜师"

# 静态资产配置
[assets]
directory = "./static"
binding = "ASSETS" 