name = "liuyao-ai"
main = "worker.js"
compatibility_date = "2025-06-11"

# 环境变量（示例）
[vars]
# API_KEY = ""
# MODEL = ""
# ENDPOINT = ""
# SYSTEM_PROMPT = ""

# 静态资产配置
[assets]
directory = "./static"
binding = "ASSETS" 